export const cardData = [
  {
    id: 'testID1',
    headerImage: './images/header2.png',
    logo: './images/logo4.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '90',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID2',
    headerImage: './images/header3.png',
    logo: './images/logo1.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '70',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID3',
    headerImage: './images/card1Head.png',
    logo: './images/logo2.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description:
      'Lorem ipsum dolor sit amet, consectetur adipiscing elit egestas blandit libero.',
    totalRaise: '100',
    start: 'April 7, 11:00 UTC',
    prize: '1 $PLACEHOLDER = 0.01 BUSD',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID4',
    headerImage: './images/card1Head.png',
    logo: './images/logo3.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID5',
    headerImage: './images/header2.png',
    logo: './images/logo5.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '90',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID6',
    headerImage: './images/header2.png',
    logo: './images/logo6.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '90',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID7',
    headerImage: './images/card1Head.png',
    logo: './images/logo1.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID8',
    headerImage: './images/header2.png',
    logo: './images/logo2.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '90',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID9',
    headerImage: './images/card1Head.png',
    logo: './images/logo3.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID10',
    headerImage: './images/header2.png',
    logo: './images/logo6.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '90',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
  {
    id: 'testID11',
    headerImage: './images/card1Head.png',
    logo: './images/logo3.png',
    ProjectName: 'Project Name',
    PlaceHolder: 'Place Holder',
    description: 'lorem ispum',
    totalRaise: '100',
    start: '100',
    prize: '100',
    percentage: '80',
    allocationPrize: '300 BUSD',
    ClaimDate: '2022-Apr-15 13:00 UTC',
  },
];
